version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TLS_VERSION: "1.2"
    ports:
      - "1444:1433" # Proper port mapping: host:container
    networks:
      - shared_network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose WebAPI on port 8080
      - "8081:8081" # Expose WebAPI on port 8081
    depends_on:
      - sqlserver
    networks:
      - shared_network
networks:
  shared_network:
    driver: bridge
